# Generated by Django 4.2.6 on 2023-11-09 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_ordered_date_alter_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 9, 3, 6, 41, 975884, tzinfo=datetime.timezone.utc)),
        ),
    ]
